# Generated by Django 3.0.6 on 2020-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(upload_to='mediafiles/home/%Y/%m/%d')),
                ('name', models.CharField(max_length=32)),
                ('is_banner', models.BooleanField(default=False)),
                ('is_card', models.BooleanField(default=False)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('seo_desc', models.CharField(blank=True, max_length=256, null=True)),
                ('seo_key', models.CharField(blank=True, max_length=128, null=True)),
                ('is_use', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
