# Generated by Django 3.0.6 on 2020-06-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64, unique=True, verbose_name='产品大类')),
                ('item_child', models.CharField(blank=True, max_length=64, null=True, verbose_name='产品子类')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=64)),
                ('s_addr', models.CharField(blank=True, max_length=128, null=True)),
                ('s_manager', models.CharField(blank=True, max_length=32, null=True)),
                ('s_contact', models.CharField(max_length=32)),
                ('s_email', models.EmailField(max_length=254)),
                ('s_mobile', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='mask', max_length=32, verbose_name='产品名称')),
                ('pro_desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='seo描述')),
                ('pro_keywords', models.CharField(blank=True, max_length=128, null=True, verbose_name='seo关键词')),
                ('pro_type', models.CharField(default='None', max_length=32, verbose_name='规格型号')),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='产品单价($)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='产品类别')),
                ('pro_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Suppliers', verbose_name='供应商')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cover', models.BooleanField(default=False, verbose_name='是否封面')),
                ('image', models.ImageField(upload_to='mediafiles/product/%Y/%m/%d')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products', verbose_name='产品名称')),
            ],
        ),
    ]
